import { useEffect, useRef, useState } from "react";
import { Link } from "react-router-dom";
import { useQueryClient } from "@tanstack/react-query";
import { projectApi, projectPath, type AuditEvent, type IngestKey, type Invite, type Member, type Role } from "../api/team";
import { useProject, useTeam, useTeamPages } from "./context";
import { Action, Badge, DateTime, Empty, ErrorNotice, Field, Heading, Input, Loading, More, Select, Textarea, useTask } from "./common";

export function AdminPage({ kind }: { kind: "members" | "keys" | "audit" }) {
  const project = useProject();
  if (project.role !== "admin") return <div className="team-page"><Empty title="Administrator access required"><p>Your current role can inspect project evidence. Project administration requires an admin role.</p><Link to={projectPath(project.id)}>Return to overview</Link></Empty></div>;
  return kind === "members" ? <MembersPage /> : kind === "keys" ? <KeysPage /> : <AuditPage />;
}
function Roles({ value, onChange }: { value: Role; onChange: (value: Role) => void }) { return <Select aria-label="Role" value={value} onChange={event => onChange(event.target.value as Role)}><option value="viewer">Viewer</option><option value="editor">Editor</option><option value="admin">Admin</option></Select>; }
function useAdminRefresh() { const project = useProject(); const queries = useQueryClient(); return () => { void queries.invalidateQueries({ predicate: query => query.queryKey.includes(project.id) }); }; }
function OneTimeSecret({ value, label, close }: { value: string; label: string; close: () => void }) {
  const task = useTask(); const [copied, setCopied] = useState(false);
  const { permissionRevisions } = useTeam(); const project = useProject();
  const permissionRevision = permissionRevisions[project.id] ?? 0; const issuedRevision = useRef(permissionRevision);
  const invalidated = issuedRevision.current !== permissionRevision;
  useEffect(() => { if (invalidated) close(); }, [invalidated, close]);
  if (invalidated) return null;
  return <section className="team-secret" aria-label={label}><h2>{label}</h2><p className="team-muted">Copy this value now. It will not be shown again after you close this panel.</p><Field label={label}><Textarea readOnly value={value} autoComplete="off" /></Field><div className="team-inline"><Action onClick={() => void task.run(() => navigator.clipboard.writeText(value), () => setCopied(true))}>{copied ? "Copied" : "Copy value"}</Action><Action onClick={close}>Hide {label.toLowerCase()}</Action></div><ErrorNotice error={task.error} /></section>;
}
function MembersPage() {
  const project = useProject(); const { client } = useTeam(); const refresh = useAdminRefresh(); const task = useTask(); const revoke = useTask();
  const members = useTeamPages<Member>([project.id, "admin", "members"], `${projectApi(project.id)}/members`); const invites = useTeamPages<Invite>([project.id, "admin", "invites"], `${projectApi(project.id)}/invites`);
  const [email, setEmail] = useState(""); const [role, setRole] = useState<Role>("viewer"); const [hours, setHours] = useState("24"); const [secret, setSecret] = useState("");
  return <div className="team-page"><Heading title="Project members">Admins manage access; editors add their own notes and checks; viewers inspect captured evidence.</Heading><ErrorNotice error={members.error} retry={() => void members.refetch()} />{members.isPending && <Loading />}
    <div className="team-list">{!members.error && members.data?.pages.flatMap(page => page.items).map(member => <MemberRow key={`${member.user.id}:${member.role}`} member={member} />)}</div><More available={members.hasNextPage} busy={members.isFetchingNextPage} onClick={() => void members.fetchNextPage()} />
    <section className="team-section"><h2>Invite a teammate</h2><p className="team-muted">You share the code manually. Account emails are login identifiers, not externally verified addresses.</p><form className="team-form team-narrow" onSubmit={event => { event.preventDefault(); setSecret(""); void task.run(() => client.request<{ invite: Invite; token: string }>(`${projectApi(project.id)}/invites`, { method: "POST", body: { email, role, expiresInHours: Number(hours) } }), value => { setSecret(value.token); setEmail(""); refresh(); }); }}>
      <Field label="Invite email"><Input type="email" required maxLength={128} value={email} onChange={event => setEmail(event.target.value)} /></Field><Field label="Invitation role"><Roles value={role} onChange={setRole} /></Field><Field label="Expires in hours"><Input type="number" min={1} max={168} required value={hours} onChange={event => setHours(event.target.value)} /></Field><ErrorNotice error={task.error} /><Action primary type="submit" disabled={task.busy}>{task.busy ? "Creating invitation…" : "Create invitation"}</Action>
    </form>{secret && <OneTimeSecret value={secret} label="Invitation code" close={() => setSecret("")} />}</section>
    <section className="team-section"><h2>Pending invitations</h2><ErrorNotice error={invites.error} retry={() => void invites.refetch()} /><ErrorNotice error={revoke.error} />{invites.isPending && <Loading />}<div className="team-list">{!invites.error && invites.data?.pages.flatMap(page => page.items).map(invite => <div className="team-row" key={invite.id}><div><strong>{invite.email}</strong><p className="team-muted">{invite.role} · Expires <DateTime value={invite.expiresAt} /></p></div><Action disabled={revoke.busy} aria-label={`Revoke invitation for ${invite.email}`} onClick={() => void revoke.run(() => client.request(`${projectApi(project.id)}/invites/${encodeURIComponent(invite.id)}`, { method: "DELETE" }), refresh)}>Revoke invitation</Action></div>)}</div><More available={invites.hasNextPage} busy={invites.isFetchingNextPage} onClick={() => void invites.fetchNextPage()} /></section>
  </div>;
}
function MemberRow({ member }: { member: Member }) {
  const project = useProject(); const { client } = useTeam(); const refresh = useAdminRefresh(); const task = useTask(); const [role, setRole] = useState(member.role); const [confirm, setConfirm] = useState(false); const base = `${projectApi(project.id)}/members/${encodeURIComponent(member.user.id)}`;
  return <div className="team-row"><div><strong>{member.user.email}</strong><p className="team-muted">Joined <DateTime value={member.joinedAt} /></p><ErrorNotice error={task.error} /></div><div className="team-row-actions"><select className="team-input" aria-label={`Role for ${member.user.email}`} value={role} onChange={event => setRole(event.target.value as Role)}><option value="viewer">Viewer</option><option value="editor">Editor</option><option value="admin">Admin</option></select><Action disabled={task.busy || role === member.role} onClick={() => void task.run(() => client.request(base, { method: "PATCH", body: { role } }), refresh)}>Save role</Action><Action disabled={task.busy} onClick={() => setConfirm(!confirm)}>Remove member</Action></div>{confirm && <div className="team-confirm"><p>Remove {member.user.email} from this project? Their other project memberships remain.</p><div className="team-inline"><Action disabled={task.busy} onClick={() => void task.run(() => client.request(base, { method: "DELETE" }), refresh)}>Confirm member removal</Action><Action onClick={() => setConfirm(false)}>Keep member</Action></div></div>}</div>;
}
function KeysPage() {
  const project = useProject(); const { client } = useTeam(); const refresh = useAdminRefresh(); const task = useTask(); const revoke = useTask(); const [label, setLabel] = useState(""); const [days, setDays] = useState("90"); const [secret, setSecret] = useState("");
  const keys = useTeamPages<IngestKey>([project.id, "admin", "keys"], `${projectApi(project.id)}/keys`);
  return <div className="team-page"><Heading title="Ingestion keys">Keys send traces into this project. They do not grant read access and remain active until expiry or revocation, even if their creator leaves.</Heading>
    <form className="team-form team-narrow" onSubmit={event => { event.preventDefault(); setSecret(""); void task.run(() => client.request<{ key: IngestKey; token: string }>(`${projectApi(project.id)}/keys`, { method: "POST", body: { label, expiresInDays: Number(days) } }), value => { setSecret(value.token); setLabel(""); refresh(); }); }}><Field label="Key label"><Input required value={label} maxLength={128} placeholder="Production support agent" onChange={event => setLabel(event.target.value)} /></Field><Field label="Expires in days"><Input required type="number" min={1} max={365} value={days} onChange={event => setDays(event.target.value)} /></Field><ErrorNotice error={task.error} /><Action primary type="submit" disabled={task.busy}>{task.busy ? "Creating key…" : "Create ingestion key"}</Action></form>{secret && <OneTimeSecret value={secret} label="Ingestion key" close={() => setSecret("")} />}
    <section className="team-section"><h2>Connect an OTLP exporter</h2><p className="team-muted">Set the full traces endpoint and Authorization header in your exporter configuration.</p><code className="team-code">{location.origin}/api/team/ingest/v1/traces</code><code className="team-code mt-2">Authorization: Bearer &lt;project ingestion key&gt;</code></section>
    <section className="team-section"><h2>Active keys</h2><ErrorNotice error={keys.error} retry={() => void keys.refetch()} /><ErrorNotice error={revoke.error} />{keys.isPending && <Loading />}<div className="team-list">{!keys.error && keys.data?.pages.flatMap(page => page.items).map(key => <div className="team-row" key={key.id}><div><strong>{key.label}</strong><p className="team-muted">{key.prefix} · Expires <DateTime value={key.expiresAt} /></p><p className="team-muted">Last used <DateTime value={key.lastUsedAt} /></p></div><Action disabled={revoke.busy} aria-label={`Revoke key ${key.label}`} onClick={() => void revoke.run(() => client.request(`${projectApi(project.id)}/keys/${encodeURIComponent(key.id)}`, { method: "DELETE" }), refresh)}>Revoke key</Action></div>)}</div><More available={keys.hasNextPage} busy={keys.isFetchingNextPage} onClick={() => void keys.fetchNextPage()} /></section>
  </div>;
}
function AuditPage() {
  const project = useProject(); const audit = useTeamPages<AuditEvent>([project.id, "admin", "audit"], `${projectApi(project.id)}/audit`);
  return <div className="team-page"><Heading title="Audit log">Recent project operations. The latest 10,000 events are retained; this is bounded operational history.</Heading><ErrorNotice error={audit.error} retry={() => void audit.refetch()} />{audit.isPending && <Loading />}<div className="team-list">{!audit.error && audit.data?.pages.flatMap(page => page.items).map(event => <article className="team-row" key={event.id}><div><strong>{event.action.replace(/[._]/g, " ")}</strong><p className="team-muted"><DateTime value={event.createdAt} /> · {event.actor.type}: {event.actor.id}</p><p className="team-muted">{event.target.type}: {event.target.id ?? "Batch"}</p><p className="team-muted">{Object.entries(event.details).map(([key, value]) => `${key}: ${value}`).join(" · ")}</p></div><Badge value={event.outcome} /></article>)}</div><More available={audit.hasNextPage} busy={audit.isFetchingNextPage} onClick={() => void audit.fetchNextPage()} /></div>;
}
