import { useEffect, useRef, useState } from "react";
import { Link, Route, Routes, useNavigate, useParams, useSearchParams } from "react-router-dom";
import { useInfiniteQuery, useQueryClient } from "@tanstack/react-query";
import { Search, X } from "lucide-react";
import { projectApi, projectPath, teamQuery, type Note, type RunDetail, type RunFilters, type RunSummary, type Span } from "../api/team";
import { useAccount, usePagePolling, useProject, useTeam, useTeamPages, useTeamQuery } from "./context";
import { Action, Badge, DateTime, Empty, ErrorNotice, Evidence, Field, Heading, Input, Loading, More, Select, Textarea, duration, useTask } from "./common";
import { IngestGuide } from "./projects";

export function TracesPage() { return <Routes><Route index element={<TraceList />} /><Route path=":runId" element={<TraceDetailPage />} /><Route path=":runId/spans/:spanId" element={<TraceDetailPage />} /></Routes>; }

function TraceList() {
  const project = useProject(); const [params, setParams] = useSearchParams(); const [q, setQ] = useState(params.get("q") ?? ""); const input = useRef<HTMLInputElement>(null);
  const urlQuery = params.get("q") ?? ""; const previousQuery = useRef(urlQuery);
  useEffect(() => { if (previousQuery.current !== urlQuery) { previousQuery.current = urlQuery; setQ(urlQuery); } }, [urlQuery]);
  const filter: RunFilters = { q: params.get("q") ?? "", status: (params.get("status") || undefined) as RunFilters["status"], model: params.get("model") ?? "", provider: params.get("provider") ?? "" };
  const result = useTeamPages<RunSummary>([project.id, "runs"], `${projectApi(project.id)}/runs`, filter, 5000);
  const items = result.data?.pages.flatMap(page => page.items) ?? [];
  const change = (key: string, value: string) => setParams(previous => { const next = new URLSearchParams(previous); if (value) next.set(key, value); else next.delete(key); return next; }, { replace: true });
  useEffect(() => { const timer = window.setTimeout(() => { if (q !== (params.get("q") ?? "")) setParams(previous => { const next = new URLSearchParams(previous); if (q) next.set("q", q); else next.delete("q"); return next; }, { replace: true }); }, 250); return () => clearTimeout(timer); }, [q, params, setParams]);
  useEffect(() => { const handler = (event: KeyboardEvent) => { const editing = event.target instanceof HTMLElement && (event.target.matches("input,textarea,select") || event.target.isContentEditable); if (event.key === "/" && !editing) { event.preventDefault(); input.current?.focus(); } if (event.key === "Escape" && document.activeElement === input.current) setQ(""); }; document.addEventListener("keydown", handler); return () => document.removeEventListener("keydown", handler); }, []);
  const filtered = Object.values(filter).some(Boolean);
  return <div className="team-page"><Heading title="Traces">Search captured inputs, outputs and span names across this project.</Heading><div className="team-filters">
    <label className="team-field team-filter-search"><span>Search traces</span><input ref={input} className="team-input" aria-label="Search traces" placeholder="Search captured evidence…" value={q} maxLength={256} onChange={event => setQ(event.target.value)} /><button type="button" aria-label={q ? "Clear trace search" : "Focus trace search"} onClick={() => { setQ(""); input.current?.focus(); }}>{q ? <X size={16} /> : <Search size={16} />}</button></label>
    <Field label="Status"><Select value={filter.status ?? ""} onChange={event => change("status", event.target.value)}><option value="">All statuses</option><option value="running">Running</option><option value="completed">Completed</option><option value="failed">Failed</option></Select></Field>
    <Field label="Model"><Input value={filter.model} maxLength={256} placeholder="Exact model" onChange={event => change("model", event.target.value)} /></Field>
    <Field label="Provider"><Input value={filter.provider} maxLength={256} placeholder="Exact provider" onChange={event => change("provider", event.target.value)} /></Field>
  </div><ErrorNotice error={result.error} retry={() => void result.refetch()} />{result.isPending && <Loading text="Searching project traces…" />}
    {!result.error && !result.isPending && <><p className="team-muted" role="status">{items.length} {items.length === 1 ? "trace" : "traces"} loaded · Refreshes while this page is open</p>{items.length ? <div className="team-list">{items.map(run => <Link className="team-row team-row-link" key={run.id} to={`${projectPath(project.id)}/traces/${encodeURIComponent(run.id)}${params.size ? `?${params}` : ""}`}><div><strong>{run.displayName || run.name}</strong><p className="team-muted"><DateTime value={run.startedAt} /> · {run.spanCount} spans · {run.model ?? "Model unavailable"}</p></div><div className="team-inline"><span className="team-muted">{duration(run.durationMs)}</span><Badge value={run.status} /></div></Link>)}</div> : filtered ? <Empty title="No matching traces"><p>Try a different phrase or clear the filters.</p><Action onClick={() => { setQ(""); setParams({}, { replace: true }); }}>Clear filters</Action></Empty> : <IngestGuide />}</>}
    <More available={result.hasNextPage} busy={result.isFetchingNextPage} onClick={() => void result.fetchNextPage()} />
  </div>;
}

function TraceDetailPage() {
  const project = useProject(); const account = useAccount(); const { client } = useTeam(); const { runId = "", spanId } = useParams(); const [params] = useSearchParams(); const navigate = useNavigate(); const task = useTask(); const [confirmDelete, setConfirmDelete] = useState(false);
  const suffix = params.size ? `?${params}` : ""; const base = `${projectApi(project.id)}/runs/${encodeURIComponent(runId)}`; const path = `${projectPath(project.id)}/traces/${encodeURIComponent(runId)}`;
  const queryKey = ["team", account.session.id, account.user.id, project.id, "run", runId];
  const detail = useInfiniteQuery({ queryKey, initialPageParam: undefined as string | undefined, queryFn: ({ signal, pageParam }) => client.request<RunDetail>(`${base}${teamQuery({ limit: 50, cursor: pageParam })}`, { signal }), getNextPageParam: page => page.spans.hasMore ? page.spans.nextCursor ?? undefined : undefined });
  usePagePolling(queryKey, 5000, detail.refetch);
  const run = detail.data?.pages[0]?.run; const spans = detail.data?.pages.flatMap(page => page.spans.items) ?? [];
  return <div className="team-page"><Link className="team-text-link" to={`${projectPath(project.id)}/traces${suffix}`}>← All traces</Link><div className="team-section" style={{ borderTop: 0, paddingTop: 0 }}><ErrorNotice error={detail.error} retry={() => void detail.refetch()} />{detail.isPending && <Loading text="Loading trace…" />}
    {run && !detail.error && <><Heading title={run.displayName || run.name} action={project.role === "admin" ? <Action onClick={() => setConfirmDelete(!confirmDelete)}>Delete trace</Action> : undefined}><Badge value={run.status} /> · <DateTime value={run.startedAt} /></Heading>
      {confirmDelete && <div className="team-confirm"><p>Delete <strong>{run.displayName || run.name}</strong> and its {run.spanCount} spans and notes? Saved checks keep their frozen evidence.</p><div className="team-inline"><Action disabled={task.busy} onClick={() => void task.run(() => client.request(base, { method: "DELETE" }), () => navigate(`${projectPath(project.id)}/traces${suffix}`, { replace: true }))}>Confirm trace deletion</Action><Action onClick={() => setConfirmDelete(false)}>Keep trace</Action></div><ErrorNotice error={task.error} /></div>}
      <dl className="team-facts"><div><dt>Duration</dt><dd>{duration(run.durationMs)}</dd></div><div><dt>Spans</dt><dd>{run.spanCount}</dd></div><div><dt>Errors</dt><dd>{run.errorCount}</dd></div><div><dt>Model / provider</dt><dd>{run.model ?? "Unavailable"} / {run.provider ?? "Unavailable"}</dd></div></dl><p className="team-muted">Trace ID: {run.id}</p>
      <div className="team-trace-grid"><section><h2>Spans</h2><p className="team-muted">{spans.length} of {run.spanCount} span summaries loaded</p><div className="team-list">{spans.map(span => <button className="team-span-button" key={span.id} aria-pressed={span.id === spanId} onClick={() => navigate(`${path}/spans/${encodeURIComponent(span.id)}${suffix}`)}><span>{span.name}<small className="team-muted block">{span.kind ?? "Span"} · {span.model ?? span.id}</small></span><span className="team-muted">{duration(span.durationMs)}</span></button>)}</div><More available={detail.hasNextPage} busy={detail.isFetchingNextPage} onClick={() => void detail.fetchNextPage()} /></section><section>{spanId ? <SpanEvidence key={spanId} base={base} spanId={spanId} /> : <Empty title="Inspect a span"><p>Select a captured step to review its input, output, attributes and recorded timing.</p></Empty>}</section></div><Notes key={runId} runId={runId} spanId={spanId} /></>}
  </div></div>;
}

function SpanEvidence({ base, spanId }: { base: string; spanId: string }) {
  const project = useProject(); const span = useTeamQuery<Span>([project.id, "span", base, spanId], `${base}/spans/${encodeURIComponent(spanId)}`, 5000);
  return <><ErrorNotice error={span.error} retry={() => void span.refetch()} />{span.isPending && <Loading text="Loading captured span…" />}{span.data && !span.error && <><h2>{span.data.name}</h2><p className="team-muted">{span.data.kind ?? "Span"} · {span.data.id}</p><dl className="team-facts"><div><dt>Input tokens</dt><dd>{span.data.inputTokens ?? "Unavailable"}</dd></div><div><dt>Output tokens</dt><dd>{span.data.outputTokens ?? "Unavailable"}</dd></div><div><dt>Duration</dt><dd>{duration(span.data.durationMs)}</dd></div></dl><Evidence title="Input" value={span.data.inputPayload} unavailable={span.data.unavailable.input} /><Evidence title="Output" value={span.data.outputPayload} unavailable={span.data.unavailable.output} /><Evidence title="Attributes" value={span.data.attributes} unavailable={span.data.unavailable.attributes} /></>}</>;
}

function Notes({ runId, spanId }: { runId: string; spanId?: string }) {
  const project = useProject(); const account = useAccount(); const { client } = useTeam(); const queries = useQueryClient(); const task = useTask();
  const base = `${projectApi(project.id)}/runs/${encodeURIComponent(runId)}/notes`; const notes = useTeamPages<Note>([project.id, "notes", runId], base, {}, 5000);
  const [text, setText] = useState(""); const [kind, setKind] = useState<Note["kind"]>("note"); const [attachSpan, setAttachSpan] = useState(false);
  const refresh = () => void queries.invalidateQueries({ predicate: query => query.queryKey.includes(project.id) && query.queryKey.includes("notes") });
  return <section className="team-section"><h2>Shared notes</h2><ErrorNotice error={notes.error} retry={() => void notes.refetch()} /><ErrorNotice error={task.error} />{notes.isPending && <Loading />}
    {!notes.error && notes.data?.pages.flatMap(page => page.items).map(note => <article className="team-note" key={note.id}><div className="team-inline"><Badge value={note.kind} /><strong>{note.author.email}</strong><span className="team-muted"><DateTime value={note.createdAt} /></span></div>{note.spanId && <p className="team-muted">Span {note.spanId}</p>}<p>{note.text}</p>{project.role !== "viewer" && note.author.id === account.user.id && <Action disabled={task.busy} aria-label={`Delete your ${note.kind}`} onClick={() => void task.run(() => client.request(`${base}/${encodeURIComponent(note.id)}`, { method: "DELETE" }), refresh)}>Delete note</Action>}</article>)}
    <More available={notes.hasNextPage} busy={notes.isFetchingNextPage} onClick={() => void notes.fetchNextPage()} />
    {project.role === "viewer" ? <p className="team-muted">Viewers can read shared notes. An editor or admin role is needed to add a note.</p> : <form className="team-form team-narrow team-section" onSubmit={event => { event.preventDefault(); void task.run(async () => { if (new TextEncoder().encode(text).byteLength > 8192) throw new Error("Notes must be at most 8 KiB."); return client.request<Note>(base, { method: "POST", body: { text, kind, ...(attachSpan && spanId ? { spanId } : {}) } }); }, () => { setText(""); refresh(); }); }}><Field label="Note type"><Select value={kind} onChange={event => setKind(event.target.value as Note["kind"])}><option value="note">Note</option><option value="issue">Issue</option><option value="good">Good result</option></Select></Field><Field label="Your note" hint="Plain text. Your account is recorded as the author."><Textarea required value={text} onChange={event => setText(event.target.value)} maxLength={8192} /></Field>{spanId && <label className="team-inline"><input type="checkbox" checked={attachSpan} onChange={event => setAttachSpan(event.target.checked)} />Attach to selected span</label>}<Action primary disabled={task.busy} type="submit">{task.busy ? "Adding note…" : "Add note"}</Action></form>}
  </section>;
}
